sensor:
  - platform: rest
    name: "They said so"
    resource: "http://quotes.rest/qod.json"
    json_attributes_path: "$.contents.quotes[0]"
    value_template: "OK"
    json_attributes:
      - author
      - quote
    scan_interval: 43200